version: '3'
services:
    influxdb:
        image: 'influxdb:1.8.10'
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin

    garie-plugin:
        platform: linux/amd64
        build: .
        privileged: true
        volumes:
            - ./src:/usr/src/garie-plugin/src:z
            - ./config.json:/usr/src/garie-plugin/config.json:z
            - /var/run/docker.sock:/run/docker.sock
            - /usr/bin/docker:/bin/docker
        ports:
            - 3001:3000
        environment:
            - HOST=influxdb
        depends_on:
            - influxdb
        command: bash -c "tail -f /dev/null"

    chronograf:
        image: 'chronograf:1.8.10'
        ports:
            - 8888:8888
        depends_on:
            - influxdb
